# Generated by Django 5.1.5 on 2025-02-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
    ]
