# Generated by Django 5.1.5 on 2025-02-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_movements', '0002_stockmovementout'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockmovementin',
            table='stock_movements_in',
        ),
        migrations.AlterModelTable(
            name='stockmovementout',
            table='stock_movements_out',
        ),
    ]
